import { Inter } from "next/font/google";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import { Toaster } from "react-hot-toast";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex w-full">
      <Sidebar value="overview" />
      <div className="w-full">
      <Header />
        {children}
        <Toaster/>
      </div>

    </div>
   
  );
}
